# render.yaml
services:
  - type: web
    name: dp600-exam-prep
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
